[metadata]
name = data_suite
version = 0.1.0
description = Data-centric identification of in-distribution incongruous examples
long_description = file: README.md
long_description_content_type = text/markdown
url = https://arxiv.org/abs/2202.08836
author = Nabeel Seedat
author_email = seedatnabeel@gmail.com
license = MIT
license_files = LICENSE
classifiers =
    License :: OSI Approved :: MIT License
    Development Status :: 4 - Beta
    Programming Language :: Python
keywords = data-centric AI, data quality, uncertainty
platforms = any


[options]
zip_safe = False
packages = find_namespace:
include_package_data = True
package_dir =
    =src

python_requires = <3.10

install_requires =
    copulas==0.6.0
    nonconformist==2.1.0
    numpy
    pandas
    opentsne
    papermill
    pyod==1.0.1
    scikit-learn-extra
    scikit_learn
    scipy
    suod
    tensorflow
    torch==1.10.0
    torchvision==0.11.1
    uq360==0.2
    wandb
    xlrd==2.0.1

[options.packages.find]
where = src
exclude =
    tests

[options.extras_require]

benchmarks =
    aix360
    alibi-detect==0.9.1
    tensorflow>2

contribute =
    black
    flake8
    isort
    notebook
    pre-commit

all =
    %(benchmarks)s
    %(contribute)s
